apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cloudnative-pg
  - ../../base/kubelinks
  - ../../base/pgadmin
  - ../../base/grafana
patches:
  - path: hetznerk3s.yaml
  - path: cnpg-delete.yaml
