apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 15m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  values:
    persistence:
      defaultClass: true
      defaultFsType: ext4
      defaultClassReplicaCount: 2
      reclaimPolicy: Delete
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 2
      replicaSoftAntiAffinity: false
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
