# Password generator для основного пользователя remnawave
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: remnawave-pg-app-password
  namespace: pg-remnawave
spec:
  length: 24
  symbols: 0
---
# ExternalSecret для основного пользователя, который будет отражен в namespace remnawave
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: remnawave-pg-app-secret
  namespace: pg-remnawave
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: remnawave-pg-app-secret
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "remnawave"
      data:
        username: remnawave
        password: "{{ .password }}"
        host: remnawave-pg-rw.pg-remnawave.svc.cluster.local
        port: "5432"
        dbname: remnawave
        uri: "postgresql://remnawave:{{ .password }}@remnawave-pg-rw.pg-remnawave.svc.cluster.local:5432/remnawave"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: remnawave-pg-app-password
