---
# Отключаем Ingress для кластера talos-dev-hel1-1 
# так как используется Envoy Gateway с HTTPRoute
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: remnawave
  namespace: remnawave
spec:
  values:
    ingress:
      app:
        enabled: false
      panel:
        enabled: false
      bot:
        enabled: false
