apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/base/remnawave
  - secret-store.yaml
components:
  - ../../../apps/base/remnawave/components/gw-api
  - ../../../apps/base/remnawave/components/external-secrets
patches:
  - path: external-secret-patch.yaml
