---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: remnawave-doppler
  namespace: remnawave
spec:
  provider:
    doppler:
      project: remnawave
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            namespace: external-secrets
            key: dopplerToken
