apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      interval: 12h
  values:
    controller:
      logLevel: info
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
    speaker:
      logLevel: info
      frr:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
