# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: remnawave
  namespace: remnawave
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store # Override on cluster level
  target:
    name: remnawave-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_AUTH_SECRET
      remoteRef:
        key: JWT_AUTH_SECRET
    - secretKey: JWT_API_TOKENS_SECRET
      remoteRef:
        key: JWT_API_TOKENS_SECRET
    - secretKey: WEBHOOK_SECRET_HEADER
      remoteRef:
        key: WEBHOOK_SECRET_HEADER
    - secretKey: METRICS_USER
      remoteRef:
        key: METRICS_USER
    - secretKey: METRICS_PASS
      remoteRef:
        key: METRICS_PASS
