---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: remnawave
  namespace: remnawave
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store  # Override on cluster level
  target:
    name: remnawave-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: REMNAWAVE
