apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-public-pdb
  namespace: envoy-gateway-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: envoy-public
