apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler
spec:
  provider:
    doppler:
      project: portogate
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            namespace: external-secrets
            key: dopplerToken
